### ISSUE TITLE
qq音乐单曲解析出的flac和ape无法下载

### ISSUE THREAD

**Issue by liguge** [AnyListen/AnyListen#3]
http://c.y.qq.com/v8/playsong.html?songid=108652692&source=yqq#wechat_redirect

这是单曲的qq音乐地址

解析地址    http://stream.qqmusic.tc.qq.com/F000000ragt00UYDzz.flac   无法下载

希望能够修复一下     这歌曲发表时间    9.22

**Comment by liguge** [comment]
感觉是最新的，qq音乐收费的无损歌曲解析出的地址都无法下载了。

**Comment by AnyListen** [comment]
已修复

**Comment by liguge** [comment]
- [http://ww4.sinaimg.cn/mw690/67a8938fjw1f85z66lxrjj20qu0flmyi.jpg](url)
下载还是无法下载啊~

**Comment by liguge** [comment]
还是无法下载啊~

难道是我的网络问题？ 自带的迅雷模块也无法下载~
