### ISSUE TITLE
腾讯这厮的无损又下不了了，天天变

### ISSUE THREAD

**Issue by tsingk** [AnyListen/AnyListen#8]
case "ape":
                    return "http://stream.qqmusic.tc.qq.com/A000" + id + ".ape";
                case "flac":
                    return "http://stream.qqmusic.tc.qq.com/F000" + id + ".flac";
                case "ogg":
                    return "http://stream.qqmusic.tc.qq.com/M800" + id + ".mp3";
                default:
                    var time = new Random(DateTime.Now.Millisecond).NextDouble();
                    var key = GetKey(time.ToString(CultureInfo.CurrentCulture));
                    return quality == "128"
                        ? "http://cc.stream.qqmusic.qq.com/M500" + id + ".mp3?vkey=" + key + "&guid=" + time +
                          "&fromtag=0"
                        : "http://cc.stream.qqmusic.qq.com/M800" + id + ".mp3?vkey=" + key + "&guid=" + time +
                          "&fromtag=0";

已失效

**Comment by AnyListen** [comment]
新版的也很easy 自己研究吧
